server:
 # port: 7777
  port: 7777
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jdbc?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: sztuau123!
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    hikari:
      ddl-auto: update
      connection-init-sql: set names utf8mb4
    tomcat:
      init-s-q-l: SET NAMES utf8mb4
upload:
  activity:
    path: /home/auServerData/activities
  picture:
    path: /home/auServerData/twitter
  outlay:
    path: /home/auServerData/outlay
  synthesizesubmit:
    path: /home/auServerData/synthesizesubmit
  assLogo:
    path: /home/auServerData/assLogo

wxconfig:
  appid: wx117b9376ed2498e4
  appsecret: 3da690b8122e51168bb362c642b4de06

interviewass:
  opentime: 2021-09-23 00:00:00
  endtime: 2021-10-1 00:00:00